# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_milstd1553b', [dirname(__file__)])
        except ImportError:
            import _milstd1553b
            return _milstd1553b
        if fp is not None:
            try:
                _mod = imp.load_module('_milstd1553b', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _milstd1553b = swig_import_helper()
    del swig_import_helper
else:
    import _milstd1553b
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class WordBuffer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WordBuffer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WordBuffer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _milstd1553b.new_WordBuffer(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_WordBuffer
    __del__ = lambda self : None;
    def __getitem__(self, *args) -> "unsigned short" : return _milstd1553b.WordBuffer___getitem__(self, *args)
    def __setitem__(self, *args) -> "void" : return _milstd1553b.WordBuffer___setitem__(self, *args)
    def cast(self) -> "unsigned short *" : return _milstd1553b.WordBuffer_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _milstd1553b.WordBuffer_frompointer
    if _newclass:frompointer = staticmethod(_milstd1553b.WordBuffer_frompointer)
WordBuffer_swigregister = _milstd1553b.WordBuffer_swigregister
WordBuffer_swigregister(WordBuffer)

def WordBuffer_frompointer(*args) -> "WordBuffer *" :
  return _milstd1553b.WordBuffer_frompointer(*args)
WordBuffer_frompointer = _milstd1553b.WordBuffer_frompointer

TRUE = _milstd1553b.TRUE
FALSE = _milstd1553b.FALSE
TMK_VERSION_MIN = _milstd1553b.TMK_VERSION_MIN
TMK_VERSION = _milstd1553b.TMK_VERSION
MAX_TMK_NUMBER = _milstd1553b.MAX_TMK_NUMBER
MIN_TMK_TYPE = _milstd1553b.MIN_TMK_TYPE
MAX_TMK_TYPE = _milstd1553b.MAX_TMK_TYPE
TMK400 = _milstd1553b.TMK400
TMKMPC = _milstd1553b.TMKMPC
RTMK400 = _milstd1553b.RTMK400
TMKX = _milstd1553b.TMKX
TMKXI = _milstd1553b.TMKXI
MRTX = _milstd1553b.MRTX
MRTXI = _milstd1553b.MRTXI
TA = _milstd1553b.TA
TAI = _milstd1553b.TAI
MRTA = _milstd1553b.MRTA
MRTAI = _milstd1553b.MRTAI
ALL_TMKS = _milstd1553b.ALL_TMKS
GET_TIMEOUT = _milstd1553b.GET_TIMEOUT
SWTIMER_OFF = _milstd1553b.SWTIMER_OFF
SWTIMER_ON = _milstd1553b.SWTIMER_ON
SWTIMER_EVENT = _milstd1553b.SWTIMER_EVENT
SWTIMER_RESET = _milstd1553b.SWTIMER_RESET
GET_SWTIMER_CTRL = _milstd1553b.GET_SWTIMER_CTRL
TIMER_RESET = _milstd1553b.TIMER_RESET
TIMER_OFF = _milstd1553b.TIMER_OFF
TIMER_16BIT = _milstd1553b.TIMER_16BIT
TIMER_32BIT = _milstd1553b.TIMER_32BIT
TIMER_1US = _milstd1553b.TIMER_1US
TIMER_2US = _milstd1553b.TIMER_2US
TIMER_4US = _milstd1553b.TIMER_4US
TIMER_8US = _milstd1553b.TIMER_8US
TIMER_16US = _milstd1553b.TIMER_16US
TIMER_32US = _milstd1553b.TIMER_32US
TIMER_64US = _milstd1553b.TIMER_64US
TIMER_STOP = _milstd1553b.TIMER_STOP
TIMER_SYN = _milstd1553b.TIMER_SYN
TIMER_SYND = _milstd1553b.TIMER_SYND
TIMER_SA = _milstd1553b.TIMER_SA
TIMER_NOSTOP = _milstd1553b.TIMER_NOSTOP
TIMER_MASK = _milstd1553b.TIMER_MASK
TIMER_STEP = _milstd1553b.TIMER_STEP
TIMER_BITS = _milstd1553b.TIMER_BITS
GET_TIMER_CTRL = _milstd1553b.GET_TIMER_CTRL
DATA_BC_RT = _milstd1553b.DATA_BC_RT
DATA_BC_RT_BRCST = _milstd1553b.DATA_BC_RT_BRCST
DATA_RT_BC = _milstd1553b.DATA_RT_BC
DATA_RT_RT = _milstd1553b.DATA_RT_RT
DATA_RT_RT_BRCST = _milstd1553b.DATA_RT_RT_BRCST
CTRL_C_A = _milstd1553b.CTRL_C_A
CTRL_C_BRCST = _milstd1553b.CTRL_C_BRCST
CTRL_CD_A = _milstd1553b.CTRL_CD_A
CTRL_CD_BRCST = _milstd1553b.CTRL_CD_BRCST
CTRL_C_AD = _milstd1553b.CTRL_C_AD
BUS_A = _milstd1553b.BUS_A
BUS_B = _milstd1553b.BUS_B
BUS_1 = _milstd1553b.BUS_1
BUS_2 = _milstd1553b.BUS_2
S_ERAO_MASK = _milstd1553b.S_ERAO_MASK
S_MEO_MASK = _milstd1553b.S_MEO_MASK
S_IB_MASK = _milstd1553b.S_IB_MASK
S_TO_MASK = _milstd1553b.S_TO_MASK
S_EM_MASK = _milstd1553b.S_EM_MASK
S_EBC_MASK = _milstd1553b.S_EBC_MASK
S_DI_MASK = _milstd1553b.S_DI_MASK
S_ELN_MASK = _milstd1553b.S_ELN_MASK
S_G1_MASK = _milstd1553b.S_G1_MASK
S_G2_MASK = _milstd1553b.S_G2_MASK
NWORDS_MASK = _milstd1553b.NWORDS_MASK
CMD_MASK = _milstd1553b.CMD_MASK
SUBADDR_MASK = _milstd1553b.SUBADDR_MASK
CI_MASK = _milstd1553b.CI_MASK
HBIT_MASK = _milstd1553b.HBIT_MASK
RT_DIR_MASK = _milstd1553b.RT_DIR_MASK
ADDRESS_MASK = _milstd1553b.ADDRESS_MASK
RTFL_MASK = _milstd1553b.RTFL_MASK
DNBA_MASK = _milstd1553b.DNBA_MASK
SSFL_MASK = _milstd1553b.SSFL_MASK
BUSY_MASK = _milstd1553b.BUSY_MASK
BRCST_MASK = _milstd1553b.BRCST_MASK
NULL_MASK = _milstd1553b.NULL_MASK
SREQ_MASK = _milstd1553b.SREQ_MASK
ERROR_MASK = _milstd1553b.ERROR_MASK
SREQ = _milstd1553b.SREQ
BUSY = _milstd1553b.BUSY
SSFL = _milstd1553b.SSFL
RTFL = _milstd1553b.RTFL
DNBA = _milstd1553b.DNBA
CWB0 = _milstd1553b.CWB0
CWB1 = _milstd1553b.CWB1
BC_MODE = _milstd1553b.BC_MODE
RT_MODE = _milstd1553b.RT_MODE
MT_MODE = _milstd1553b.MT_MODE
MRT_MODE = _milstd1553b.MRT_MODE
UNDEFINED_MODE = _milstd1553b.UNDEFINED_MODE
RT_TRANSMIT = _milstd1553b.RT_TRANSMIT
RT_RECEIVE = _milstd1553b.RT_RECEIVE
RT_ERROR_MASK = _milstd1553b.RT_ERROR_MASK
RT_FLAG = _milstd1553b.RT_FLAG
RT_FLAG_MASK = _milstd1553b.RT_FLAG_MASK
RT_HBIT_MODE = _milstd1553b.RT_HBIT_MODE
RT_FLAG_MODE = _milstd1553b.RT_FLAG_MODE
RT_BRCST_MODE = _milstd1553b.RT_BRCST_MODE
RT_DATA_BL = _milstd1553b.RT_DATA_BL
RT_GENER1_BL = _milstd1553b.RT_GENER1_BL
RT_GENER2_BL = _milstd1553b.RT_GENER2_BL
BC_GENER1_BL = _milstd1553b.BC_GENER1_BL
BC_GENER2_BL = _milstd1553b.BC_GENER2_BL
MT_GENER1_BL = _milstd1553b.MT_GENER1_BL
MT_GENER2_BL = _milstd1553b.MT_GENER2_BL
TMK_IRQ_OFF = _milstd1553b.TMK_IRQ_OFF
CX_CC_MASK = _milstd1553b.CX_CC_MASK
CX_CONT_MASK = _milstd1553b.CX_CONT_MASK
CX_BUS_MASK = _milstd1553b.CX_BUS_MASK
CX_SIG_MASK = _milstd1553b.CX_SIG_MASK
CX_INT_MASK = _milstd1553b.CX_INT_MASK
CX_CONT = _milstd1553b.CX_CONT
CX_STOP = _milstd1553b.CX_STOP
CX_BUS_0 = _milstd1553b.CX_BUS_0
CX_BUS_A = _milstd1553b.CX_BUS_A
CX_BUS_1 = _milstd1553b.CX_BUS_1
CX_BUS_B = _milstd1553b.CX_BUS_B
CX_NOSIG = _milstd1553b.CX_NOSIG
CX_SIG = _milstd1553b.CX_SIG
CX_INT = _milstd1553b.CX_INT
CX_NOINT = _milstd1553b.CX_NOINT
SX_NOERR = _milstd1553b.SX_NOERR
SX_MEO = _milstd1553b.SX_MEO
SX_TOA = _milstd1553b.SX_TOA
SX_TOD = _milstd1553b.SX_TOD
SX_ELN = _milstd1553b.SX_ELN
SX_ERAO = _milstd1553b.SX_ERAO
SX_ESYN = _milstd1553b.SX_ESYN
SX_EBC = _milstd1553b.SX_EBC
SX_ERR_MASK = _milstd1553b.SX_ERR_MASK
SX_IB_MASK = _milstd1553b.SX_IB_MASK
SX_G1_MASK = _milstd1553b.SX_G1_MASK
SX_G2_MASK = _milstd1553b.SX_G2_MASK
SX_K2_MASK = _milstd1553b.SX_K2_MASK
SX_K1_MASK = _milstd1553b.SX_K1_MASK
SX_SCC_MASK = _milstd1553b.SX_SCC_MASK
SX_ME_MASK = _milstd1553b.SX_ME_MASK
SX_BUS_MASK = _milstd1553b.SX_BUS_MASK
SX_BUS_0 = _milstd1553b.SX_BUS_0
SX_BUS_A = _milstd1553b.SX_BUS_A
SX_BUS_1 = _milstd1553b.SX_BUS_1
SX_BUS_B = _milstd1553b.SX_BUS_B
GET_IO_DELAY = _milstd1553b.GET_IO_DELAY
RT_ENABLE = _milstd1553b.RT_ENABLE
RT_DISABLE = _milstd1553b.RT_DISABLE
RT_GET_ENABLE = _milstd1553b.RT_GET_ENABLE
CMD_DYNAMIC_BUS_CONTROL = _milstd1553b.CMD_DYNAMIC_BUS_CONTROL
CMD_SYNCHRONIZE = _milstd1553b.CMD_SYNCHRONIZE
CMD_TRANSMIT_STATUS_WORD = _milstd1553b.CMD_TRANSMIT_STATUS_WORD
CMD_INITIATE_SELF_TEST = _milstd1553b.CMD_INITIATE_SELF_TEST
CMD_TRANSMITTER_SHUTDOWN = _milstd1553b.CMD_TRANSMITTER_SHUTDOWN
CMD_OVERRIDE_TRANSMITTER_SHUTDOWN = _milstd1553b.CMD_OVERRIDE_TRANSMITTER_SHUTDOWN
CMD_INHIBIT_TERMINAL_FLAG_BIT = _milstd1553b.CMD_INHIBIT_TERMINAL_FLAG_BIT
CMD_OVERRIDE_INHIBIT_TERMINAL_FLAG_BIT = _milstd1553b.CMD_OVERRIDE_INHIBIT_TERMINAL_FLAG_BIT
CMD_RESET_REMOTE_TERMINAL = _milstd1553b.CMD_RESET_REMOTE_TERMINAL
CMD_TRANSMIT_VECTOR_WORD = _milstd1553b.CMD_TRANSMIT_VECTOR_WORD
CMD_SYNCHRONIZE_WITH_DATA_WORD = _milstd1553b.CMD_SYNCHRONIZE_WITH_DATA_WORD
CMD_TRANSMIT_LAST_COMMAND_WORD = _milstd1553b.CMD_TRANSMIT_LAST_COMMAND_WORD
CMD_TRANSMIT_BUILT_IN_TEST_WORD = _milstd1553b.CMD_TRANSMIT_BUILT_IN_TEST_WORD
TMK_BAD_0 = _milstd1553b.TMK_BAD_0
TMK_BAD_TYPE = _milstd1553b.TMK_BAD_TYPE
TMK_BAD_IRQ = _milstd1553b.TMK_BAD_IRQ
TMK_BAD_NUMBER = _milstd1553b.TMK_BAD_NUMBER
BC_BAD_BUS = _milstd1553b.BC_BAD_BUS
BC_BAD_BASE = _milstd1553b.BC_BAD_BASE
BC_BAD_LEN = _milstd1553b.BC_BAD_LEN
RT_BAD_PAGE = _milstd1553b.RT_BAD_PAGE
RT_BAD_LEN = _milstd1553b.RT_BAD_LEN
RT_BAD_ADDRESS = _milstd1553b.RT_BAD_ADDRESS
RT_BAD_FUNC = _milstd1553b.RT_BAD_FUNC
BC_BAD_FUNC = _milstd1553b.BC_BAD_FUNC
TMK_BAD_FUNC = _milstd1553b.TMK_BAD_FUNC
VTMK_BAD_VERSION = _milstd1553b.VTMK_BAD_VERSION
class TTmkConfigData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TTmkConfigData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TTmkConfigData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nType"] = _milstd1553b.TTmkConfigData_nType_set
    __swig_getmethods__["nType"] = _milstd1553b.TTmkConfigData_nType_get
    if _newclass:nType = _swig_property(_milstd1553b.TTmkConfigData_nType_get, _milstd1553b.TTmkConfigData_nType_set)
    __swig_setmethods__["szName"] = _milstd1553b.TTmkConfigData_szName_set
    __swig_getmethods__["szName"] = _milstd1553b.TTmkConfigData_szName_get
    if _newclass:szName = _swig_property(_milstd1553b.TTmkConfigData_szName_get, _milstd1553b.TTmkConfigData_szName_set)
    __swig_setmethods__["wPorts1"] = _milstd1553b.TTmkConfigData_wPorts1_set
    __swig_getmethods__["wPorts1"] = _milstd1553b.TTmkConfigData_wPorts1_get
    if _newclass:wPorts1 = _swig_property(_milstd1553b.TTmkConfigData_wPorts1_get, _milstd1553b.TTmkConfigData_wPorts1_set)
    __swig_setmethods__["wPorts2"] = _milstd1553b.TTmkConfigData_wPorts2_set
    __swig_getmethods__["wPorts2"] = _milstd1553b.TTmkConfigData_wPorts2_get
    if _newclass:wPorts2 = _swig_property(_milstd1553b.TTmkConfigData_wPorts2_get, _milstd1553b.TTmkConfigData_wPorts2_set)
    __swig_setmethods__["wIrq1"] = _milstd1553b.TTmkConfigData_wIrq1_set
    __swig_getmethods__["wIrq1"] = _milstd1553b.TTmkConfigData_wIrq1_get
    if _newclass:wIrq1 = _swig_property(_milstd1553b.TTmkConfigData_wIrq1_get, _milstd1553b.TTmkConfigData_wIrq1_set)
    __swig_setmethods__["wIrq2"] = _milstd1553b.TTmkConfigData_wIrq2_set
    __swig_getmethods__["wIrq2"] = _milstd1553b.TTmkConfigData_wIrq2_get
    if _newclass:wIrq2 = _swig_property(_milstd1553b.TTmkConfigData_wIrq2_get, _milstd1553b.TTmkConfigData_wIrq2_set)
    __swig_setmethods__["wIODelay"] = _milstd1553b.TTmkConfigData_wIODelay_set
    __swig_getmethods__["wIODelay"] = _milstd1553b.TTmkConfigData_wIODelay_get
    if _newclass:wIODelay = _swig_property(_milstd1553b.TTmkConfigData_wIODelay_get, _milstd1553b.TTmkConfigData_wIODelay_set)
    def __init__(self): 
        this = _milstd1553b.new_TTmkConfigData()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TTmkConfigData
    __del__ = lambda self : None;
TTmkConfigData_swigregister = _milstd1553b.TTmkConfigData_swigregister
TTmkConfigData_swigregister(TTmkConfigData)

class TBc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TBc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TBc, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wResult"] = _milstd1553b.TBc_wResult_set
    __swig_getmethods__["wResult"] = _milstd1553b.TBc_wResult_get
    if _newclass:wResult = _swig_property(_milstd1553b.TBc_wResult_get, _milstd1553b.TBc_wResult_set)
    __swig_setmethods__["wAW1"] = _milstd1553b.TBc_wAW1_set
    __swig_getmethods__["wAW1"] = _milstd1553b.TBc_wAW1_get
    if _newclass:wAW1 = _swig_property(_milstd1553b.TBc_wAW1_get, _milstd1553b.TBc_wAW1_set)
    __swig_setmethods__["wAW2"] = _milstd1553b.TBc_wAW2_set
    __swig_getmethods__["wAW2"] = _milstd1553b.TBc_wAW2_get
    if _newclass:wAW2 = _swig_property(_milstd1553b.TBc_wAW2_get, _milstd1553b.TBc_wAW2_set)
    def __init__(self): 
        this = _milstd1553b.new_TBc()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TBc
    __del__ = lambda self : None;
TBc_swigregister = _milstd1553b.TBc_swigregister
TBc_swigregister(TBc)

class TBcx(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TBcx, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TBcx, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wBase"] = _milstd1553b.TBcx_wBase_set
    __swig_getmethods__["wBase"] = _milstd1553b.TBcx_wBase_get
    if _newclass:wBase = _swig_property(_milstd1553b.TBcx_wBase_get, _milstd1553b.TBcx_wBase_set)
    __swig_setmethods__["wResultX"] = _milstd1553b.TBcx_wResultX_set
    __swig_getmethods__["wResultX"] = _milstd1553b.TBcx_wResultX_get
    if _newclass:wResultX = _swig_property(_milstd1553b.TBcx_wResultX_get, _milstd1553b.TBcx_wResultX_set)
    def __init__(self): 
        this = _milstd1553b.new_TBcx()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TBcx
    __del__ = lambda self : None;
TBcx_swigregister = _milstd1553b.TBcx_swigregister
TBcx_swigregister(TBcx)

class TRt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TRt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TRt, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wStatus"] = _milstd1553b.TRt_wStatus_set
    __swig_getmethods__["wStatus"] = _milstd1553b.TRt_wStatus_get
    if _newclass:wStatus = _swig_property(_milstd1553b.TRt_wStatus_get, _milstd1553b.TRt_wStatus_set)
    __swig_setmethods__["wCmd"] = _milstd1553b.TRt_wCmd_set
    __swig_getmethods__["wCmd"] = _milstd1553b.TRt_wCmd_get
    if _newclass:wCmd = _swig_property(_milstd1553b.TRt_wCmd_get, _milstd1553b.TRt_wCmd_set)
    def __init__(self): 
        this = _milstd1553b.new_TRt()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TRt
    __del__ = lambda self : None;
TRt_swigregister = _milstd1553b.TRt_swigregister
TRt_swigregister(TRt)

class TMt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TMt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TMt, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wBase"] = _milstd1553b.TMt_wBase_set
    __swig_getmethods__["wBase"] = _milstd1553b.TMt_wBase_get
    if _newclass:wBase = _swig_property(_milstd1553b.TMt_wBase_get, _milstd1553b.TMt_wBase_set)
    __swig_setmethods__["wResultX"] = _milstd1553b.TMt_wResultX_set
    __swig_getmethods__["wResultX"] = _milstd1553b.TMt_wResultX_get
    if _newclass:wResultX = _swig_property(_milstd1553b.TMt_wResultX_get, _milstd1553b.TMt_wResultX_set)
    def __init__(self): 
        this = _milstd1553b.new_TMt()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TMt
    __del__ = lambda self : None;
TMt_swigregister = _milstd1553b.TMt_swigregister
TMt_swigregister(TMt)

class TMrt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TMrt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TMrt, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wStatus"] = _milstd1553b.TMrt_wStatus_set
    __swig_getmethods__["wStatus"] = _milstd1553b.TMrt_wStatus_get
    if _newclass:wStatus = _swig_property(_milstd1553b.TMrt_wStatus_get, _milstd1553b.TMrt_wStatus_set)
    def __init__(self): 
        this = _milstd1553b.new_TMrt()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TMrt
    __del__ = lambda self : None;
TMrt_swigregister = _milstd1553b.TMrt_swigregister
TMrt_swigregister(TMrt)

class TTmk(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TTmk, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TTmk, name)
    __repr__ = _swig_repr
    __swig_setmethods__["wRequest"] = _milstd1553b.TTmk_wRequest_set
    __swig_getmethods__["wRequest"] = _milstd1553b.TTmk_wRequest_get
    if _newclass:wRequest = _swig_property(_milstd1553b.TTmk_wRequest_get, _milstd1553b.TTmk_wRequest_set)
    def __init__(self): 
        this = _milstd1553b.new_TTmk()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TTmk
    __del__ = lambda self : None;
TTmk_swigregister = _milstd1553b.TTmk_swigregister
TTmk_swigregister(TTmk)

class TSub(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TSub, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TSub, name)
    __repr__ = _swig_repr
    __swig_setmethods__["bc"] = _milstd1553b.TSub_bc_set
    __swig_getmethods__["bc"] = _milstd1553b.TSub_bc_get
    if _newclass:bc = _swig_property(_milstd1553b.TSub_bc_get, _milstd1553b.TSub_bc_set)
    __swig_setmethods__["bcx"] = _milstd1553b.TSub_bcx_set
    __swig_getmethods__["bcx"] = _milstd1553b.TSub_bcx_get
    if _newclass:bcx = _swig_property(_milstd1553b.TSub_bcx_get, _milstd1553b.TSub_bcx_set)
    __swig_setmethods__["rt"] = _milstd1553b.TSub_rt_set
    __swig_getmethods__["rt"] = _milstd1553b.TSub_rt_get
    if _newclass:rt = _swig_property(_milstd1553b.TSub_rt_get, _milstd1553b.TSub_rt_set)
    __swig_setmethods__["mt"] = _milstd1553b.TSub_mt_set
    __swig_getmethods__["mt"] = _milstd1553b.TSub_mt_get
    if _newclass:mt = _swig_property(_milstd1553b.TSub_mt_get, _milstd1553b.TSub_mt_set)
    __swig_setmethods__["mrt"] = _milstd1553b.TSub_mrt_set
    __swig_getmethods__["mrt"] = _milstd1553b.TSub_mrt_get
    if _newclass:mrt = _swig_property(_milstd1553b.TSub_mrt_get, _milstd1553b.TSub_mrt_set)
    __swig_setmethods__["tmk"] = _milstd1553b.TSub_tmk_set
    __swig_getmethods__["tmk"] = _milstd1553b.TSub_tmk_get
    if _newclass:tmk = _swig_property(_milstd1553b.TSub_tmk_get, _milstd1553b.TSub_tmk_set)
    def __init__(self): 
        this = _milstd1553b.new_TSub()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TSub
    __del__ = lambda self : None;
TSub_swigregister = _milstd1553b.TSub_swigregister
TSub_swigregister(TSub)

class TTmkEventData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TTmkEventData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TTmkEventData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nInt"] = _milstd1553b.TTmkEventData_nInt_set
    __swig_getmethods__["nInt"] = _milstd1553b.TTmkEventData_nInt_get
    if _newclass:nInt = _swig_property(_milstd1553b.TTmkEventData_nInt_get, _milstd1553b.TTmkEventData_nInt_set)
    __swig_setmethods__["wMode"] = _milstd1553b.TTmkEventData_wMode_set
    __swig_getmethods__["wMode"] = _milstd1553b.TTmkEventData_wMode_get
    if _newclass:wMode = _swig_property(_milstd1553b.TTmkEventData_wMode_get, _milstd1553b.TTmkEventData_wMode_set)
    __swig_setmethods__["sub"] = _milstd1553b.TTmkEventData_sub_set
    __swig_getmethods__["sub"] = _milstd1553b.TTmkEventData_sub_get
    if _newclass:sub = _swig_property(_milstd1553b.TTmkEventData_sub_get, _milstd1553b.TTmkEventData_sub_set)
    def __init__(self): 
        this = _milstd1553b.new_TTmkEventData()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _milstd1553b.delete_TTmkEventData
    __del__ = lambda self : None;
TTmkEventData_swigregister = _milstd1553b.TTmkEventData_swigregister
TTmkEventData_swigregister(TTmkEventData)

TMK_IOC_MAGIC = _milstd1553b.TMK_IOC_MAGIC
TMK_IOC0 = _milstd1553b.TMK_IOC0
VTMK_tmkconfig = _milstd1553b.VTMK_tmkconfig
VTMK_tmkdone = _milstd1553b.VTMK_tmkdone
VTMK_tmkgetmaxn = _milstd1553b.VTMK_tmkgetmaxn
VTMK_tmkselect = _milstd1553b.VTMK_tmkselect
VTMK_tmkselected = _milstd1553b.VTMK_tmkselected
VTMK_tmkgetmode = _milstd1553b.VTMK_tmkgetmode
VTMK_tmksetcwbits = _milstd1553b.VTMK_tmksetcwbits
VTMK_tmkclrcwbits = _milstd1553b.VTMK_tmkclrcwbits
VTMK_tmkgetcwbits = _milstd1553b.VTMK_tmkgetcwbits
VTMK_tmkwaitevents = _milstd1553b.VTMK_tmkwaitevents
VTMK_tmkgetevd = _milstd1553b.VTMK_tmkgetevd
VTMK_bcreset = _milstd1553b.VTMK_bcreset
VTMK_bc_def_tldw = _milstd1553b.VTMK_bc_def_tldw
VTMK_bc_enable_di = _milstd1553b.VTMK_bc_enable_di
VTMK_bc_disable_di = _milstd1553b.VTMK_bc_disable_di
VTMK_bcdefirqmode = _milstd1553b.VTMK_bcdefirqmode
VTMK_bcgetirqmode = _milstd1553b.VTMK_bcgetirqmode
VTMK_bcgetmaxbase = _milstd1553b.VTMK_bcgetmaxbase
VTMK_bcdefbase = _milstd1553b.VTMK_bcdefbase
VTMK_bcgetbase = _milstd1553b.VTMK_bcgetbase
VTMK_bcputw = _milstd1553b.VTMK_bcputw
VTMK_bcgetw = _milstd1553b.VTMK_bcgetw
VTMK_bcgetansw = _milstd1553b.VTMK_bcgetansw
VTMK_bcputblk = _milstd1553b.VTMK_bcputblk
VTMK_bcgetblk = _milstd1553b.VTMK_bcgetblk
VTMK_bcdefbus = _milstd1553b.VTMK_bcdefbus
VTMK_bcgetbus = _milstd1553b.VTMK_bcgetbus
VTMK_bcstart = _milstd1553b.VTMK_bcstart
VTMK_bcstartx = _milstd1553b.VTMK_bcstartx
VTMK_bcdeflink = _milstd1553b.VTMK_bcdeflink
VTMK_bcgetlink = _milstd1553b.VTMK_bcgetlink
VTMK_bcstop = _milstd1553b.VTMK_bcstop
VTMK_bcgetstate = _milstd1553b.VTMK_bcgetstate
VTMK_rtreset = _milstd1553b.VTMK_rtreset
VTMK_rtdefirqmode = _milstd1553b.VTMK_rtdefirqmode
VTMK_rtgetirqmode = _milstd1553b.VTMK_rtgetirqmode
VTMK_rtdefmode = _milstd1553b.VTMK_rtdefmode
VTMK_rtgetmode = _milstd1553b.VTMK_rtgetmode
VTMK_rtgetmaxpage = _milstd1553b.VTMK_rtgetmaxpage
VTMK_rtdefpage = _milstd1553b.VTMK_rtdefpage
VTMK_rtgetpage = _milstd1553b.VTMK_rtgetpage
VTMK_rtdefpagepc = _milstd1553b.VTMK_rtdefpagepc
VTMK_rtdefpagebus = _milstd1553b.VTMK_rtdefpagebus
VTMK_rtgetpagepc = _milstd1553b.VTMK_rtgetpagepc
VTMK_rtgetpagebus = _milstd1553b.VTMK_rtgetpagebus
VTMK_rtdefaddress = _milstd1553b.VTMK_rtdefaddress
VTMK_rtgetaddress = _milstd1553b.VTMK_rtgetaddress
VTMK_rtdefsubaddr = _milstd1553b.VTMK_rtdefsubaddr
VTMK_rtgetsubaddr = _milstd1553b.VTMK_rtgetsubaddr
VTMK_rtputw = _milstd1553b.VTMK_rtputw
VTMK_rtgetw = _milstd1553b.VTMK_rtgetw
VTMK_rtputblk = _milstd1553b.VTMK_rtputblk
VTMK_rtgetblk = _milstd1553b.VTMK_rtgetblk
VTMK_rtsetanswbits = _milstd1553b.VTMK_rtsetanswbits
VTMK_rtclranswbits = _milstd1553b.VTMK_rtclranswbits
VTMK_rtgetanswbits = _milstd1553b.VTMK_rtgetanswbits
VTMK_rtgetflags = _milstd1553b.VTMK_rtgetflags
VTMK_rtputflags = _milstd1553b.VTMK_rtputflags
VTMK_rtsetflag = _milstd1553b.VTMK_rtsetflag
VTMK_rtclrflag = _milstd1553b.VTMK_rtclrflag
VTMK_rtgetflag = _milstd1553b.VTMK_rtgetflag
VTMK_rtgetstate = _milstd1553b.VTMK_rtgetstate
VTMK_rtbusy = _milstd1553b.VTMK_rtbusy
VTMK_rtlock = _milstd1553b.VTMK_rtlock
VTMK_rtunlock = _milstd1553b.VTMK_rtunlock
VTMK_rtgetcmddata = _milstd1553b.VTMK_rtgetcmddata
VTMK_rtputcmddata = _milstd1553b.VTMK_rtputcmddata
VTMK_mtreset = _milstd1553b.VTMK_mtreset
VTMK_mtdefirqmode = _milstd1553b.VTMK_mtdefirqmode
VTMK_mtgetirqmode = _milstd1553b.VTMK_mtgetirqmode
VTMK_mtgetmaxbase = _milstd1553b.VTMK_mtgetmaxbase
VTMK_mtdefbase = _milstd1553b.VTMK_mtdefbase
VTMK_mtgetbase = _milstd1553b.VTMK_mtgetbase
VTMK_mtputw = _milstd1553b.VTMK_mtputw
VTMK_mtgetw = _milstd1553b.VTMK_mtgetw
VTMK_mtgetsw = _milstd1553b.VTMK_mtgetsw
VTMK_mtputblk = _milstd1553b.VTMK_mtputblk
VTMK_mtgetblk = _milstd1553b.VTMK_mtgetblk
VTMK_mtstartx = _milstd1553b.VTMK_mtstartx
VTMK_mtdeflink = _milstd1553b.VTMK_mtdeflink
VTMK_mtgetlink = _milstd1553b.VTMK_mtgetlink
VTMK_mtstop = _milstd1553b.VTMK_mtstop
VTMK_mtgetstate = _milstd1553b.VTMK_mtgetstate
VTMK_tmkgetinfo = _milstd1553b.VTMK_tmkgetinfo
VTMK_GetVersion = _milstd1553b.VTMK_GetVersion
VTMK_rtenable = _milstd1553b.VTMK_rtenable
VTMK_mrtgetmaxn = _milstd1553b.VTMK_mrtgetmaxn
VTMK_mrtconfig = _milstd1553b.VTMK_mrtconfig
VTMK_mrtselected = _milstd1553b.VTMK_mrtselected
VTMK_mrtgetstate = _milstd1553b.VTMK_mrtgetstate
VTMK_mrtdefbrcsubaddr0 = _milstd1553b.VTMK_mrtdefbrcsubaddr0
VTMK_mrtreset = _milstd1553b.VTMK_mrtreset
VTMK_tmktimer = _milstd1553b.VTMK_tmktimer
VTMK_tmkgettimer = _milstd1553b.VTMK_tmkgettimer
VTMK_tmkgettimerl = _milstd1553b.VTMK_tmkgettimerl
VTMK_bcgetmsgtime = _milstd1553b.VTMK_bcgetmsgtime
VTMK_mtgetmsgtime = _milstd1553b.VTMK_mtgetmsgtime
VTMK_rtgetmsgtime = _milstd1553b.VTMK_rtgetmsgtime
VTMK_tmkgethwver = _milstd1553b.VTMK_tmkgethwver
VTMK_tmkgetevtime = _milstd1553b.VTMK_tmkgetevtime
VTMK_tmkswtimer = _milstd1553b.VTMK_tmkswtimer
VTMK_tmkgetswtimer = _milstd1553b.VTMK_tmkgetswtimer
VTMK_tmktimeout = _milstd1553b.VTMK_tmktimeout
VTMK_mrtdefbrcpage = _milstd1553b.VTMK_mrtdefbrcpage
VTMK_mrtgetbrcpage = _milstd1553b.VTMK_mrtgetbrcpage
TMK_IOC_MAXNR = _milstd1553b.TMK_IOC_MAXNR

def TmkOpen() -> "int" :
  return _milstd1553b.TmkOpen()
TmkOpen = _milstd1553b.TmkOpen

def TmkClose() -> "void" :
  return _milstd1553b.TmkClose()
TmkClose = _milstd1553b.TmkClose

def tmkgetmaxn() -> "int" :
  return _milstd1553b.tmkgetmaxn()
tmkgetmaxn = _milstd1553b.tmkgetmaxn

def tmkconfig(*args) -> "int" :
  return _milstd1553b.tmkconfig(*args)
tmkconfig = _milstd1553b.tmkconfig

def tmkdone(*args) -> "int" :
  return _milstd1553b.tmkdone(*args)
tmkdone = _milstd1553b.tmkdone

def tmkselect(*args) -> "int" :
  return _milstd1553b.tmkselect(*args)
tmkselect = _milstd1553b.tmkselect

def tmkselected() -> "int" :
  return _milstd1553b.tmkselected()
tmkselected = _milstd1553b.tmkselected

def tmkgetmode() -> "unsigned short" :
  return _milstd1553b.tmkgetmode()
tmkgetmode = _milstd1553b.tmkgetmode

def tmksetcwbits(*args) -> "void" :
  return _milstd1553b.tmksetcwbits(*args)
tmksetcwbits = _milstd1553b.tmksetcwbits

def tmkclrcwbits(*args) -> "void" :
  return _milstd1553b.tmkclrcwbits(*args)
tmkclrcwbits = _milstd1553b.tmkclrcwbits

def tmkgetcwbits() -> "unsigned short" :
  return _milstd1553b.tmkgetcwbits()
tmkgetcwbits = _milstd1553b.tmkgetcwbits

def tmkgetevd(*args) -> "void" :
  return _milstd1553b.tmkgetevd(*args)
tmkgetevd = _milstd1553b.tmkgetevd

def tmkwaitevents(*args) -> "int" :
  return _milstd1553b.tmkwaitevents(*args)
tmkwaitevents = _milstd1553b.tmkwaitevents

def bcreset() -> "int" :
  return _milstd1553b.bcreset()
bcreset = _milstd1553b.bcreset

def bcdefirqmode(*args) -> "int" :
  return _milstd1553b.bcdefirqmode(*args)
bcdefirqmode = _milstd1553b.bcdefirqmode

def bcgetirqmode() -> "unsigned short" :
  return _milstd1553b.bcgetirqmode()
bcgetirqmode = _milstd1553b.bcgetirqmode

def bcgetmaxbase() -> "unsigned short" :
  return _milstd1553b.bcgetmaxbase()
bcgetmaxbase = _milstd1553b.bcgetmaxbase

def bcdefbase(*args) -> "int" :
  return _milstd1553b.bcdefbase(*args)
bcdefbase = _milstd1553b.bcdefbase

def bcgetbase() -> "unsigned short" :
  return _milstd1553b.bcgetbase()
bcgetbase = _milstd1553b.bcgetbase

def bcputw(*args) -> "void" :
  return _milstd1553b.bcputw(*args)
bcputw = _milstd1553b.bcputw

def bcgetw(*args) -> "unsigned short" :
  return _milstd1553b.bcgetw(*args)
bcgetw = _milstd1553b.bcgetw

def bcgetansw(*args) -> "unsigned int" :
  return _milstd1553b.bcgetansw(*args)
bcgetansw = _milstd1553b.bcgetansw

def bcputblk(*args) -> "void" :
  return _milstd1553b.bcputblk(*args)
bcputblk = _milstd1553b.bcputblk

def bcgetblk(*args) -> "void" :
  return _milstd1553b.bcgetblk(*args)
bcgetblk = _milstd1553b.bcgetblk

def bcdefbus(*args) -> "int" :
  return _milstd1553b.bcdefbus(*args)
bcdefbus = _milstd1553b.bcdefbus

def bcgetbus() -> "unsigned short" :
  return _milstd1553b.bcgetbus()
bcgetbus = _milstd1553b.bcgetbus

def bcstart(*args) -> "int" :
  return _milstd1553b.bcstart(*args)
bcstart = _milstd1553b.bcstart

def bcstartx(*args) -> "int" :
  return _milstd1553b.bcstartx(*args)
bcstartx = _milstd1553b.bcstartx

def bcdeflink(*args) -> "int" :
  return _milstd1553b.bcdeflink(*args)
bcdeflink = _milstd1553b.bcdeflink

def bcgetlink() -> "unsigned int" :
  return _milstd1553b.bcgetlink()
bcgetlink = _milstd1553b.bcgetlink

def bcstop() -> "unsigned short" :
  return _milstd1553b.bcstop()
bcstop = _milstd1553b.bcstop

def bcgetstate() -> "unsigned int" :
  return _milstd1553b.bcgetstate()
bcgetstate = _milstd1553b.bcgetstate

def rtreset() -> "int" :
  return _milstd1553b.rtreset()
rtreset = _milstd1553b.rtreset

def rtdefirqmode(*args) -> "int" :
  return _milstd1553b.rtdefirqmode(*args)
rtdefirqmode = _milstd1553b.rtdefirqmode

def rtgetirqmode() -> "unsigned short" :
  return _milstd1553b.rtgetirqmode()
rtgetirqmode = _milstd1553b.rtgetirqmode

def rtdefmode(*args) -> "int" :
  return _milstd1553b.rtdefmode(*args)
rtdefmode = _milstd1553b.rtdefmode

def rtgetmode() -> "unsigned short" :
  return _milstd1553b.rtgetmode()
rtgetmode = _milstd1553b.rtgetmode

def rtgetmaxpage() -> "unsigned short" :
  return _milstd1553b.rtgetmaxpage()
rtgetmaxpage = _milstd1553b.rtgetmaxpage

def rtdefpage(*args) -> "int" :
  return _milstd1553b.rtdefpage(*args)
rtdefpage = _milstd1553b.rtdefpage

def rtgetpage() -> "unsigned short" :
  return _milstd1553b.rtgetpage()
rtgetpage = _milstd1553b.rtgetpage

def rtdefpagepc(*args) -> "int" :
  return _milstd1553b.rtdefpagepc(*args)
rtdefpagepc = _milstd1553b.rtdefpagepc

def rtdefpagebus(*args) -> "int" :
  return _milstd1553b.rtdefpagebus(*args)
rtdefpagebus = _milstd1553b.rtdefpagebus

def rtgetpagepc() -> "unsigned short" :
  return _milstd1553b.rtgetpagepc()
rtgetpagepc = _milstd1553b.rtgetpagepc

def rtgetpagebus() -> "unsigned short" :
  return _milstd1553b.rtgetpagebus()
rtgetpagebus = _milstd1553b.rtgetpagebus

def rtdefaddress(*args) -> "int" :
  return _milstd1553b.rtdefaddress(*args)
rtdefaddress = _milstd1553b.rtdefaddress

def rtgetaddress() -> "unsigned short" :
  return _milstd1553b.rtgetaddress()
rtgetaddress = _milstd1553b.rtgetaddress

def rtdefsubaddr(*args) -> "void" :
  return _milstd1553b.rtdefsubaddr(*args)
rtdefsubaddr = _milstd1553b.rtdefsubaddr

def rtgetsubaddr() -> "unsigned short" :
  return _milstd1553b.rtgetsubaddr()
rtgetsubaddr = _milstd1553b.rtgetsubaddr

def rtputw(*args) -> "void" :
  return _milstd1553b.rtputw(*args)
rtputw = _milstd1553b.rtputw

def rtgetw(*args) -> "unsigned short" :
  return _milstd1553b.rtgetw(*args)
rtgetw = _milstd1553b.rtgetw

def rtputblk(*args) -> "void" :
  return _milstd1553b.rtputblk(*args)
rtputblk = _milstd1553b.rtputblk

def rtgetblk(*args) -> "void" :
  return _milstd1553b.rtgetblk(*args)
rtgetblk = _milstd1553b.rtgetblk

def rtsetanswbits(*args) -> "void" :
  return _milstd1553b.rtsetanswbits(*args)
rtsetanswbits = _milstd1553b.rtsetanswbits

def rtclranswbits(*args) -> "void" :
  return _milstd1553b.rtclranswbits(*args)
rtclranswbits = _milstd1553b.rtclranswbits

def rtgetanswbits() -> "unsigned short" :
  return _milstd1553b.rtgetanswbits()
rtgetanswbits = _milstd1553b.rtgetanswbits

def rtgetflags(*args) -> "void" :
  return _milstd1553b.rtgetflags(*args)
rtgetflags = _milstd1553b.rtgetflags

def rtputflags(*args) -> "void" :
  return _milstd1553b.rtputflags(*args)
rtputflags = _milstd1553b.rtputflags

def rtsetflag() -> "void" :
  return _milstd1553b.rtsetflag()
rtsetflag = _milstd1553b.rtsetflag

def rtclrflag() -> "void" :
  return _milstd1553b.rtclrflag()
rtclrflag = _milstd1553b.rtclrflag

def rtgetflag(*args) -> "unsigned short" :
  return _milstd1553b.rtgetflag(*args)
rtgetflag = _milstd1553b.rtgetflag

def rtgetstate() -> "unsigned short" :
  return _milstd1553b.rtgetstate()
rtgetstate = _milstd1553b.rtgetstate

def rtbusy() -> "unsigned short" :
  return _milstd1553b.rtbusy()
rtbusy = _milstd1553b.rtbusy

def rtlock(*args) -> "void" :
  return _milstd1553b.rtlock(*args)
rtlock = _milstd1553b.rtlock

def rtunlock() -> "void" :
  return _milstd1553b.rtunlock()
rtunlock = _milstd1553b.rtunlock

def rtgetcmddata(*args) -> "unsigned short" :
  return _milstd1553b.rtgetcmddata(*args)
rtgetcmddata = _milstd1553b.rtgetcmddata

def rtputcmddata(*args) -> "void" :
  return _milstd1553b.rtputcmddata(*args)
rtputcmddata = _milstd1553b.rtputcmddata

def mtreset() -> "int" :
  return _milstd1553b.mtreset()
mtreset = _milstd1553b.mtreset

def mtgetsw() -> "unsigned short" :
  return _milstd1553b.mtgetsw()
mtgetsw = _milstd1553b.mtgetsw

def rtenable(*args) -> "unsigned short" :
  return _milstd1553b.rtenable(*args)
rtenable = _milstd1553b.rtenable

def mrtgetmaxn() -> "int" :
  return _milstd1553b.mrtgetmaxn()
mrtgetmaxn = _milstd1553b.mrtgetmaxn

def mrtconfig(*args) -> "unsigned int" :
  return _milstd1553b.mrtconfig(*args)
mrtconfig = _milstd1553b.mrtconfig

def mrtselected() -> "int" :
  return _milstd1553b.mrtselected()
mrtselected = _milstd1553b.mrtselected

def mrtgetstate() -> "unsigned short" :
  return _milstd1553b.mrtgetstate()
mrtgetstate = _milstd1553b.mrtgetstate

def mrtdefbrcsubaddr0() -> "void" :
  return _milstd1553b.mrtdefbrcsubaddr0()
mrtdefbrcsubaddr0 = _milstd1553b.mrtdefbrcsubaddr0

def mrtreset() -> "int" :
  return _milstd1553b.mrtreset()
mrtreset = _milstd1553b.mrtreset

def tmktimer(*args) -> "unsigned short" :
  return _milstd1553b.tmktimer(*args)
tmktimer = _milstd1553b.tmktimer

def tmkgettimer() -> "unsigned int" :
  return _milstd1553b.tmkgettimer()
tmkgettimer = _milstd1553b.tmkgettimer

def tmkgettimerl() -> "unsigned short" :
  return _milstd1553b.tmkgettimerl()
tmkgettimerl = _milstd1553b.tmkgettimerl

def bcgetmsgtime() -> "unsigned int" :
  return _milstd1553b.bcgetmsgtime()
bcgetmsgtime = _milstd1553b.bcgetmsgtime

def rtgetmsgtime() -> "unsigned int" :
  return _milstd1553b.rtgetmsgtime()
rtgetmsgtime = _milstd1553b.rtgetmsgtime

def tmkgethwver() -> "unsigned short" :
  return _milstd1553b.tmkgethwver()
tmkgethwver = _milstd1553b.tmkgethwver

def tmkgetevtime() -> "unsigned int" :
  return _milstd1553b.tmkgetevtime()
tmkgetevtime = _milstd1553b.tmkgetevtime

def tmkswtimer(*args) -> "unsigned short" :
  return _milstd1553b.tmkswtimer(*args)
tmkswtimer = _milstd1553b.tmkswtimer

def tmkgetswtimer() -> "unsigned int" :
  return _milstd1553b.tmkgetswtimer()
tmkgetswtimer = _milstd1553b.tmkgetswtimer

def tmktimeout(*args) -> "unsigned short" :
  return _milstd1553b.tmktimeout(*args)
tmktimeout = _milstd1553b.tmktimeout

def mrtdefbrcpage(*args) -> "int" :
  return _milstd1553b.mrtdefbrcpage(*args)
mrtdefbrcpage = _milstd1553b.mrtdefbrcpage

def mrtgetbrcpage() -> "unsigned short" :
  return _milstd1553b.mrtgetbrcpage()
mrtgetbrcpage = _milstd1553b.mrtgetbrcpage
# This file is compatible with both classic and new-style classes.


